# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: Paper To Code
# practice 컬렉션 새로 만들고, 이 컬렉션은 _practice/ 폴더를 자동으로 연결하여 하위 파일들 글로 인식
collections:
  practice:
    output: true 
    # 글들을 최종 웹사이트에 출력
# Description of the Site
description: AI에 대해 꾸준히 배우고 기록하는 공간
# URL of Image of the Site
site-image: /WhatATheme/assets/images/background_ai.avif
# Keywords of the Site
site-keywords: Python, Data Analysis, Statistics, Network, Machinelearning, Deep Learning, Pytorch, Computer Vision
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/PaperToCode/PaperToCode.github.io/refs/heads/main/assets/images/background_ai.avif

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: alswn7212@gmail.com
facebook_username:
twitter_username:
instagram_username:
linkedin_username:
github_username:  PaperToCode
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Name of the Author
author-name: PaperToCode
# URL for the Image of the Author
author-image: https://github.com/PaperToCode/PaperToCode.github.io/blob/main/assets/images/PAPERTOCODE_logo.png?raw=true
# 60 Words About the Author
author-about: I'm PaperToCode, and i live by pursuing work that makes my heart race. Regardless of my academic background, I believe that a strong desire to achieve something brings me closer to my goals. With consistent effort and perseverance, i actively shape myself into someone who ultimately accomplishes what I've set out to do. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://papertocode.github.io/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
